### ISSUE TITLE
File publiccode.yml errato

### ISSUE THREAD

**Issue by libremente** [regione-marche/praticheUSR-cittadini#1]
Buongiorno @sergio-villarreal,
al momento la scheda pubblicata nel catalogo di Developer Italia (https://developers.italia.it/it/software/r_marche-regione-marche-praticheusr-cittadini) presenta delle informazioni non legate al progetto (penso si tratti di un file ancora da compilare).
Quando sarà possibile compilare tale file?
Ricordo che l'editor è disponibile [qui](https://publiccode-editor.developers.italia.it/)

Resto a disposizione,
Grazie!

**Comment by Andreailsergio** [comment]
Buonasera Leonardo, ci chiedevamo anche noi perché le informazioni non si aggiornassero sul catalogo Developers. 
Il 22 gennaio abbiamo pubblicato il publiccode.yml aggiornato sul ns GitHub (https://github.com/regione-marche/praticheUSR-cittadini/blob/master/publiccode.yml).
Potete verificare se c’è un problema che impedisce la sincronizzazione ?

Grazie mille

Andrea

**Comment by libremente** [comment]
@Andreailsergio In #2 ho provato a formulare una proposta di PR.
